name: streamlit app ci

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy: 
      matrix:
        node-version: [14.x, 16.x]
        
      steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version}}
          
      - name: Install dependencies
        run: npm install
        working-directory: ./fleetmanagementclient
      - name: Run tests
        run: npm test
        working-directory: ./fleetmanagementclient 
